DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS students;

DROP TABLE IF EXISTS courses;
DROP TABLE IF EXISTS disciplines;
DROP TABLE IF EXISTS assignments;
DROP TABLE IF EXISTS enrollments;

DROP TABLE IF EXISTS grades;
DROP TABLE IF EXISTS exams;